/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkhello_JniTest */

#ifndef _Included_com_example_ndkhello_JniTest
#define _Included_com_example_ndkhello_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkhello_JniTest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkhello_JniTest_add

  (JNIEnv *env, jobject jo, jint ji1, jint ji2){
	return ji1 + ji2;
  };

#ifdef __cplusplus
}
#endif
#endif
